'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {assemble}=require('../tools/assemble-source.cjs');
const {materialize}=require('../tools/materialize-target.cjs');
test('Chakshu uses the external GPIO5 / D4 NeoPixel and never repurposes SD chip-select as status LED',()=>{
 const source=materialize(assemble(),'xiao-esp32s3-sense-8m');
 const start=source.indexOf('void updateStatusLed(bool force) {');
 const led=source.slice(start,source.indexOf('void setDeviceState(',start));
 assert.match(source,/constexpr uint8_t RGB_LED_PIN = 5;/);
 assert.match(source,/Adafruit_NeoPixel statusLed\(1, RGB_LED_PIN, NEO_GRB \+ NEO_KHZ800\)/);
 assert.match(led,/statusLed\.setPixelColor/);
 assert.match(led,/statusLed\.show\(\)/);
 assert.match(source,/constexpr uint8_t LED_DIM = 2;/);
 assert.match(led,/DeviceState::DISCONNECTED[\s\S]*Dark by default for maximum battery life/);
 assert.match(led,/DeviceState::CONNECTED_IDLE[\s\S]*Dark by default for maximum battery life/);
 assert.match(led,/DeviceState::STREAMING[\s\S]*now%5000u<20u/);
 assert.doesNotMatch(led,/now%5000u<35u|now%6000u<30u|now%1800u<45u/);
 assert.doesNotMatch(source,/Adafruit_NeoPixel statusLed\(1,\s*(?:21|LED_BUILTIN)/);
 assert.doesNotMatch(source,/pinMode\(LED_BUILTIN|digitalWrite\(LED_BUILTIN/);
 assert.match(source,/constexpr uint8_t SD_SCK=7,SD_MISO=8,SD_MOSI=9,SD_CS=21/);
 assert.match(source,/pinMode\(SD_CS,OUTPUT\)/);
 assert.match(source,/digitalWrite\(SD_CS,HIGH\)/);
 assert.match(source,/SD\.begin\(SD_CS,SPI/);
});
